Devlog
--------------------
v0.2

1.added the function to use 3 conditions to validate the raw data

----------------------
v0.3

1. optimized the algorithm to reduce running time

----------------------
v0.4

1. added the percentage comparison function

----------------------
v0.5

1. added the function to compare subcategory rating

----------------------
v0.6

1. filtered raw_df and resorted the code

----------------------
v0.7 

1. fixed some issues with name length

2. read in both audited raw data and full raw data for comparison and computing respectively

----------------------
v0.8

1. added the usage of voided flag

In [144]:
import pandas as pd
import time
from tqdm import tqdm
import math
from collections import defaultdict
from decimal import Decimal, ROUND_HALF_UP
from math import ceil

#pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', None)
pd.reset_option('display.max_rows')

# Input Report Data

In [145]:
report_df = pd.read_csv('C:/Hanbo Wang/Report_Readin_2023_ELA.csv', low_memory=False, index_col=0)

# Rename the 'grade' column to 'Summarized_Grade'
report_df = report_df.rename(columns={'Grade': 'Summarized_Grade'})
report_df = report_df.rename(columns={'Student_Performance_Score': 'Scale_Score_-_Science'})

In [146]:
report_df[report_df['LASID'].astype(str).str.strip() == '2755822848']

,Page_Number,Advanced_School_Percentage,Advanced_School_System_Percentage,Advanced_State_Percentage,Mastery_School_Percentage,Mastery_School_System_Percentage,Mastery_State_Percentage,Basic_School_Percentage,Basic_School_System_Percentage,Basic_State_Percentage,Approaching_Basic_School_Percentage,Approaching_Basic_School_System_Percentage,Approaching_Basic_State_Percentage,Unsatisfactory_School_Percentage,Unsatisfactory_School_System_Percentage,Unsatisfactory_State_Percentage,Scale_Score_-_ELA,If_Voided,Report_Title,Report_Subject,Report_Season_Year,Student_Name,Summarized_Grade,LASID,School_System_Average_Score,State_Average_Score,Student_Performance_Level,School_System_Average_Level,State_Average_Level,Student_Performance_Achievement_Level,School_System_Average_Achievement_Level,State_Average_Achievement_Level_Fixed,Reading_Performance_Achievement_Level,Literary_Text_Achievement_Level,Informational_Text_Achievement_Level,Vocabulary_Achievement_Level,Writing_Performance_Achievement_Level,Written_Expression_Achievement_Level,Knowledge&Use_of_Language_Conventions,State_Average_Achievement_Level,Reading_Performance_Achievement_Level_State_Percentage_Strong,Reading_Performance_Achievement_Level_State_Percentage_Moderate,Reading_Performance_Achievement_Level_State_Percentage_Weak,Writing_Performance_Achievement_Level_State_Percentage_Strong,Writing_Performance_Achievement_Level_State_Percentage_Moderate,Writing_Performance_Achievement_Level_State_Percentage_Weak,Student_First_Name,Student_Middle_Initial,Student_Last_Name,Summarized_DOB_Day,Summarized_DOB_Month,Summarized_DOB_Year,School_Code,School_Name,School_System_Code,School_System_Name
38883,38883,42%,8%,7%,50%,25%,32%,6%,26%,28%,≤1%,25%,22%,≤1%,16%,10%,740,False,LEAP 2025,English Language Arts,Spring 2023,SOPHIA AGUILUZ,6,2755822848,736.0,741,3.0,3.0,3,BASIC,SIC,BASIC,MODERATE PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,NaN,38%,30%,32%,46%,23%,31%,SOPHIA,NaN,AGUILUZ,21.0,8.0,2011.0,105,Patrick F. Taylor Science & Technology A,026,Jefferson Parish

In [147]:

# Assuming 'column_name' is the name of the column you want to check for duplicates
has_duplicates = report_df['LASID'].duplicated().any()

if has_duplicates:
    print("Duplicate values exist in the column.")
else:
    print("No duplicate values in the column.")

Duplicate values exist in the column.

In [148]:
report_df[report_df.duplicated(subset='LASID', keep=False)]

,Page_Number,Advanced_School_Percentage,Advanced_School_System_Percentage,Advanced_State_Percentage,Mastery_School_Percentage,Mastery_School_System_Percentage,Mastery_State_Percentage,Basic_School_Percentage,Basic_School_System_Percentage,Basic_State_Percentage,Approaching_Basic_School_Percentage,Approaching_Basic_School_System_Percentage,Approaching_Basic_State_Percentage,Unsatisfactory_School_Percentage,Unsatisfactory_School_System_Percentage,Unsatisfactory_State_Percentage,Scale_Score_-_ELA,If_Voided,Report_Title,Report_Subject,Report_Season_Year,Student_Name,Summarized_Grade,LASID,School_System_Average_Score,State_Average_Score,Student_Performance_Level,School_System_Average_Level,State_Average_Level,Student_Performance_Achievement_Level,School_System_Average_Achievement_Level,State_Average_Achievement_Level_Fixed,Reading_Performance_Achievement_Level,Literary_Text_Achievement_Level,Informational_Text_Achievement_Level,Vocabulary_Achievement_Level,Writing_Performance_Achievement_Level,Written_Expression_Achievement_Level,Knowledge&Use_of_Language_Conventions,State_Average_Achievement_Level,Reading_Performance_Achievement_Level_State_Percentage_Strong,Reading_Performance_Achievement_Level_State_Percentage_Moderate,Reading_Performance_Achievement_Level_State_Percentage_Weak,Writing_Performance_Achievement_Level_State_Percentage_Strong,Writing_Performance_Achievement_Level_State_Percentage_Moderate,Writing_Performance_Achievement_Level_State_Percentage_Weak,Student_First_Name,Student_Middle_Initial,Student_Last_Name,Summarized_DOB_Day,Summarized_DOB_Month,Summarized_DOB_Year,School_Code,School_Name,School_System_Code,School_System_Name
49100,43536,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,664,False,LEAP 2025,English Language Arts,Spring 2023,NO NAME PROVIDED,3,----------,727.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,NO,NaN,NaN,NaN,NaN,NaN,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49101,43537,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,774,False,LEAP 2025,English Language Arts,Spring 2023,NO NAME PROVIDED,3,----------,727.0,740,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,NO,NaN,NaN,NaN,NaN,NaN,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49111,43547,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,756,False,LEAP 2025,English Language Arts,Spring 2023,ZYRHIA BROWN,3,8115546526,727.0,740,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,MODERATE PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,ZYRHIA,NaN,BROWN,22.0,12.0,2013.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49112,43548,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,741,False,LEAP 2025,English Language Arts,Spring 2023,ZYRHIA BROWN,3,8115546526,727.0,740,3.0,3.0,3,BASIC,SIC,BASIC,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,ZYRHIA,NaN,BROWN,22.0,12.0,2013.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49119,43555,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,747,False,LEAP 2025,English Language Arts,Spring 2023,JAKAI CRAFT,3,7963733563,727.0,740,3.0,3.0,3,BASIC,SIC,BASIC,MODERATE PERFORMANCE,WEAK PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,JAKAI,NaN,CRAFT,14.0,4.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49120,43556,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,689,False,LEAP 2025,English Language Arts,Spring 2023,JAKAI CRAFT,3,7963733563,727.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,JAKAI,NaN,CRAFT,14.0,4.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49144,43580,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,672,False,LEAP 2025,English Language Arts,Spring 2023,AALIYAH MCDONNELL,3,9926556272,727.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,AALIYAH,NaN,MCDONNELL,24.0,5.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49145,43581,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,694,False,LEAP 2025,English Language Arts,Spring 2023,AALIYAH MCDONNELL,3,9926556272,727.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,AALIYAH,NaN,MCDONNELL,24.0,5.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49146,43582,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,787,False,LEAP 2025,English Language Arts,Spring 2023,JORDYN MCGOWAN,3,6754855134,727.0,740,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,JORDYN,NaN,MCGOWAN,21.0,7.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49147,43583,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,804,False,LEAP 2025,English Language Arts,Spring 2023,JORDYN MCGOWAN,3,6754855134,727.0,740,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,JORDYN,NaN,MCGOWAN,21.0,7.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49149,43585,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,672,False,LEAP 2025,English Language Arts,Spring 2023,DANTE MITCHELL,3,2519633875,727.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,DANTE,NaN,MITCHELL,10.0,2.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49150,43586,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,678,False,LEAP 2025,English Language Arts,Spring 2023,DANTE MITCHELL,3,2519633875,727.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,DANTE,NaN,MITCHELL,10.0,2.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49159,43595,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,732,False,LEAP 2025,English Language Arts,Spring 2023,LUV POLLARD,3,8449479371,727.0,740,3.0,3.0,3,BASIC,SIC,BASIC,WEAK PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,LUV,NaN,POLLARD,25.0,2.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49160,43596,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,698,False,LEAP 2025,English Language Arts,Spring 2023,LUV POLLARD,3,8449479371,727.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,LUV,NaN,POLLARD,25.0,2.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49166,43602,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,689,False,LEAP 2025,English Language Arts,Spring 2023,ALI SATCHER,3,5976195296,727.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,ALI,NaN,SATCHER,26.0,12.0,2013.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49167,43603,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,654,False,LEAP 2025,English Language Arts,Spring 2023,ALI SATCHER,3,5976195296,727.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,ALI,NaN,SATCHER,26.0,12.0,2013.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49182,43618,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,759,False,LEAP 2025,English Language Arts,Spring 2023,LJAH WILLIAMS,3,7654288379,727.0,740,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,MODERATE PERFORMANCE,STRONG PERFORMANCE,WEAK PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,LJAH,NaN,WILLIAMS,22.0,2.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish
49183,43619,3%,6%,6%,34%,25%,36%,20%,17%,20%,19%,18%,16%,24%,34%,22%,753,False,LEAP 2025,English Language Arts,Spring 2023,LJAH WILLIAMS,3,7654288379,727.0,740,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,MODERATE PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,LJAH,NaN,WILLIAMS,22.0,2.0,2014.0,11,Mary Bethune Elementary Literature Techn,R36,Orleans Parish

In [149]:

#report_df = report_df.drop(report_df.columns[0], axis=1)

report_df

,Page_Number,Advanced_School_Percentage,Advanced_School_System_Percentage,Advanced_State_Percentage,Mastery_School_Percentage,Mastery_School_System_Percentage,Mastery_State_Percentage,Basic_School_Percentage,Basic_School_System_Percentage,Basic_State_Percentage,Approaching_Basic_School_Percentage,Approaching_Basic_School_System_Percentage,Approaching_Basic_State_Percentage,Unsatisfactory_School_Percentage,Unsatisfactory_School_System_Percentage,Unsatisfactory_State_Percentage,Scale_Score_-_ELA,If_Voided,Report_Title,Report_Subject,Report_Season_Year,Student_Name,Summarized_Grade,LASID,School_System_Average_Score,State_Average_Score,Student_Performance_Level,School_System_Average_Level,State_Average_Level,Student_Performance_Achievement_Level,School_System_Average_Achievement_Level,State_Average_Achievement_Level_Fixed,Reading_Performance_Achievement_Level,Literary_Text_Achievement_Level,Informational_Text_Achievement_Level,Vocabulary_Achievement_Level,Writing_Performance_Achievement_Level,Written_Expression_Achievement_Level,Knowledge&Use_of_Language_Conventions,State_Average_Achievement_Level,Reading_Performance_Achievement_Level_State_Percentage_Strong,Reading_Performance_Achievement_Level_State_Percentage_Moderate,Reading_Performance_Achievement_Level_State_Percentage_Weak,Writing_Performance_Achievement_Level_State_Percentage_Strong,Writing_Performance_Achievement_Level_State_Percentage_Moderate,Writing_Performance_Achievement_Level_State_Percentage_Weak,Student_First_Name,Student_Middle_Initial,Student_Last_Name,Summarized_DOB_Day,Summarized_DOB_Month,Summarized_DOB_Year,School_Code,School_Name,School_System_Code,School_System_Name
0,22256,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,695,False,LEAP 2025,English Language Arts,Spring 2023,CHRISTIAN FRANCIS,3,7831378545,744.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,CHRISTIAN,NaN,FRANCIS,29.0,7.0,2013.0,71,Magnolia Elementary,023,Iberia Parish
1,22257,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,685,False,LEAP 2025,English Language Arts,Spring 2023,MIGUEL GAGE,3,5412525873,744.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,MIGUEL,NaN,GAGE,12.0,2.0,2012.0,71,Magnolia Elementary,023,Iberia Parish
2,22258,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,717,False,LEAP 2025,English Language Arts,Spring 2023,EZAVIEN GREEN,3,8828116684,744.0,740,2.0,3.0,3,APPROACHING BASIC,SIC,BASIC,MODERATE PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,EZAVIEN,NaN,GREEN,10.0,8.0,2014.0,71,Magnolia Elementary,023,Iberia Parish
3,22259,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,720,False,LEAP 2025,English Language Arts,Spring 2023,AYCETON HALL,3,1271283891,744.0,740,2.0,3.0,3,APPROACHING BASIC,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,AYCETON,NaN,HALL,25.0,8.0,2014.0,71,Magnolia Elementary,023,Iberia Parish
4,22260,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,685,False,LEAP 2025,English Language Arts,Spring 2023,ZAKHARIA HAWK,3,8934384727,744.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,ZAKHARIA,NaN,HAWK,19.0,7.0,2014.0,71,Magnolia Elementary,023,Iberia Parish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66762,66762,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,773,False,LEAP 2025,English Language Arts,Spring 2023,SKY WILLIAMS,8,4186498644,739.0,746,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,SKY,NaN,WILLIAMS,29.0,6.0,2009.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish
66763,66763,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,709,False,LEAP 2025,English Language Arts,Spring 2023,ELIJAH WILLIAMSON,8,5648689233,739.0,746,2.0,3.0,3,APPROACHING BASIC,SIC,BASIC,WEAK PERFORMANCE,STRONG PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,ELIJAH,NaN,WILLIAMSON,29.0,10.0,2007.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish
66764,66764,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,717,False,LEAP 2025,English Language Arts,Spring 2023,JONTAE WILLIS,8,9832174422,739.0,746,2.0,3.0,3,APPROACHING BASIC,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,JONTAE,NaN,WILLIS,29.0,10.0,2008.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish
66765,66765,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,727,False,LEAP 2025,English Language Arts,Spring 2023,DEMARI WILSON,8,7326166781,739.0,746,3.0,3.0,3,BASIC,SIC,BASIC,MODERATE PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,DEMARI,NaN,WILSON,20.0,1.0,2009.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish
66766,66766,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,765,False,LEAP 2025,English Language Arts,Spring 2023,CORAAN WRIGHT,8,7928932334,739.0,746,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,MODERATE PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,CORAAN,NaN,WRIGHT,13.0,2.0,2009.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish

In [150]:
report_subjects = report_df['Report_Subject'].unique()

print(report_subjects)
if len(report_subjects) == 1:
    subject = report_subjects[0].strip().replace(' ', '_')
if subject == 'English_Language_Arts':
    subject = 'ELA'
subject

['English Language Arts']

'ELA'

In [151]:
subject

'ELA'

In [152]:
report_schools = report_df[['School_Code', 'School_Name']].drop_duplicates()






r_school_df = report_schools

# Input LDESTD Data

In [153]:
#Generate list of variables by subjects we got from reports
subject_variable_list = []

subject_variable_list.append(f"Scale_Score_-_{subject}")
subject_variable_list.append(f"Assessment_Achievement_Level_-_{subject}")
subject_variable_list.append(f"Summarized_Void_Flag_-_{subject}")
subject_variable_list.append(f"Test_Taken_Flag_-_{subject}")
subject_variable_list.append(f"Launch_Flag_-_{subject}")

In [154]:
#Generate the total variable list we need to extract from LDESTD
raw_variable_list = ['DRC_Unique_Student_ID','Student_First_Name','Student_Middle_Initial','Student_Last_Name', 'LASID', 
                     'Summarized_DOB_Month', 
                     'Summarized_DOB_Day', 'Summarized_DOB_Year', 'Summarized_Grade',  
                      'School_Name', 'School_Code', 'School_System_Name', 'School_System_Code', 'Site_Report_Code', 
                     'Summarize_to_Assessment_Group_Code_for_School_System_level_reporting',
                     "Show_'N/A'_in_place_of_School_System_results_on_school_reports",
                     'Assess_Group_Type', 'Rollup_to_State' 
                    ]

subcategory_variable_list = ['Reading_Rating_', 'Literary_Text_Rating', 'Informational_Text_Rating', 'Vocabulary_Rating', 'Written_Expression_Rating', 
                            'Knowledge_&_Use_of_Language_Conventions_Rating', 'Writing_Rating']

variable_list = raw_variable_list + subject_variable_list + subcategory_variable_list

In [155]:
raw_audit_df = pd.read_csv('c:/Hanbo Wang/LEAP/2023/LDESTD/ldestd_2023_audit.csv', usecols=variable_list, low_memory=False)

raw_df = pd.read_csv('c:/Hanbo Wang/LEAP/2023/LDESTD/ldestd_2023.csv', usecols=variable_list, low_memory=False)

In [156]:
# Filter the DataFrame
raw_df = raw_df.loc[(raw_df[f'Test_Taken_Flag_-_{subject}'] == 'Y') | 
                    (raw_df[f'Summarized_Void_Flag_-_{subject}'] == 'Y') | 
                    (raw_df[f'Launch_Flag_-_{subject}'] == 'Y')]

In [157]:
# Filter the DataFrame
raw_audit_df = raw_audit_df.loc[(raw_audit_df[f'Test_Taken_Flag_-_{subject}'] == 'Y') | 
                    (raw_audit_df[f'Summarized_Void_Flag_-_{subject}'] == 'Y') | 
                    (raw_audit_df[f'Launch_Flag_-_{subject}'] == 'Y')]

In [158]:
raw_df

,School_System_Code,School_Code,School_System_Name,School_Name,DRC_Unique_Student_ID,Student_Last_Name,Student_First_Name,Student_Middle_Initial,LASID,Summarized_Grade,Summarized_DOB_Month,Summarized_DOB_Day,Summarized_DOB_Year,Scale_Score_-_ELA,Assessment_Achievement_Level_-_ELA,Literary_Text_Rating,Informational_Text_Rating,Vocabulary_Rating,Written_Expression_Rating,Knowledge_&_Use_of_Language_Conventions_Rating,Reading_Rating_,Writing_Rating,Test_Taken_Flag_-_ELA,Summarized_Void_Flag_-_ELA,Assess_Group_Type,Launch_Flag_-_ELA,Rollup_to_State,Summarize_to_Assessment_Group_Code_for_School_System_level_reporting,Show_'N/A'_in_place_of_School_System_results_on_school_reports,Site_Report_Code
0,001,1,Acadia Parish,Armstrong Middle School,75,DUG,Z,,9296198755,8,,10,,678,UNS,1,1,1,1,1,1,1,Y,,1,Y,Y,N,N,001
1,W7B,1,Lafayette Charter Foundation,Lafayette Renaissance Charter Academy,86,ESP,A,,2822358915,7,,07,,760,MAS,3,3,2,2,2,3,3,Y,,3,Y,Y,N,Y,W7B001
2,001,1,Acadia Parish,Armstrong Middle School,97,GAB,M,,6713794564,6,,27,,735,BAS,1,3,2,2,3,2,2,Y,,1,Y,Y,N,N,001
3,001,1,Acadia Parish,Armstrong Middle School,98,GAR,M,,7637485129,7,,11,,716,APP,3,1,1,1,2,1,1,Y,,1,Y,Y,N,N,001
4,001,1,Acadia Parish,Armstrong Middle School,142,JAC,C,,6854518148,6,,01,,656,UNS,1,1,1,1,1,1,1,Y,,1,Y,Y,N,N,001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307951,044,8,St. Bernard Parish,J.F. Gauthier School,306411,HOL,A,,9721893382,5,,15,,737,BAS,1,1,1,3,3,1,3,Y,,1,Y,Y,N,N,044
307952,052,21,St. Tammany Parish,Little Oak Middle School,306725,PRO,L,,3355313866,4,,28,,752,MAS,3,2,2,3,1,3,2,Y,,1,Y,Y,N,N,052
307953,052,33,St. Tammany Parish,St. Tammany Junior High School,306765,SHE,T,,4696485927,8,,26,,779,MAS,3,3,3,2,2,3,2,Y,,1,Y,Y,N,N,052
307954,052,36,St. Tammany Parish,Sixth Ward Elementary School,306772,RES,A,,6878634393,3,,12,,732,BAS,1,3,1,2,1,2,2,Y,,1,,Y,N,N,052
307955,052,47,St. Tammany Parish,Honey Island Elementary School,306786,BRA,T,,3287322842,3,,26,,713,APP,1,1,1,2,1,1,2,Y,,1,,Y,N,N,052

In [159]:
raw_df['Summarized_Void_Flag_-_ELA'].value_counts()

Summarized_Void_Flag_-_ELA
     279938
2        97
1        92
4        27
Name: count, dtype: int64

In [160]:
# Get the unique school names from r_school_df
r_school_names = r_school_df['School_Name']



total_schools = raw_df['School_Name'].unique()

total_school_codes = raw_df['School_Code'].unique()

r_school_df['Name_Is_Valid'] = r_school_df['School_Name'].apply(lambda x: x.strip() in ''.join(total_schools) if isinstance(x, str) else False)

r_school_df['Code_Is_Valid'] = r_school_df['School_Code'].astype(str).apply(lambda x: x.strip() in [str(code).zfill(3) for code in total_school_codes])

# Assuming 'column_name' is the name of the column you want to check for duplicates
has_duplicates = raw_df['DRC_Unique_Student_ID'].duplicated().any()

if has_duplicates:
    print("Duplicate values exist in the column.")
else:
    print("No duplicate values in the column.")

raw_df[(raw_df['School_System_Name'].str.strip() == 'East Baton Rouge Parish' ) & (raw_df['Summarized_Grade'] == 5) & (raw_df['Summarized_Void_Flag_-_ELA'].str.strip() != ('2' and '1'))]['Scale_Score_-_ELA'].sum()/2945

raw_df["Show_'N/A'_in_place_of_School_System_results_on_school_reports"].value_counts()

raw_df[raw_df['LASID'] == 'XXXXX52192' ]

raw_df[raw_df['Summarized_Grade'] == 7]['Assessment_Achievement_Level_-_Science'].value_counts()

raw_df[raw_df['Summarized_Grade'] == 7]['Assessment_Achievement_Level_-_Science'].value_counts().sum()

53307-498

## modify report data based on raw data

In [162]:
def modify_report_data(report_df, raw_df):
    # Create a dictionary from raw_df for faster access
    raw_dict = defaultdict(list)
    for i, row in raw_df.iterrows():
        raw_dict[row['LASID']].append(row)

    # Prepare dictionaries to store the changes we want to make
    changes_school_system_code = {}
    changes_school_system_name = {}
    changes_lasid = {}

    # Iterate over the rows in report_df
    for index, report_row in report_df.iterrows():
        lasid = report_row['LASID']
        # Check if the LASID exists in raw_df
        if lasid in raw_dict:
            # Get the corresponding rows in the raw_df DataFrame
            raw_rows = raw_dict[lasid]
            # Iterate over the raw_rows
            for raw_row in raw_rows:
                if str(raw_row['Site_Report_Code']).strip() == 'R36' and (raw_row[f'Test_Taken_Flag_-_{subject}'] == 'Y' or raw_row[f'Summarized_Void_Flag_-_{subject}'] == 'Y' or raw_row[f'Launch_Flag_-_{subject}'] == 'Y'):
                    changes_school_system_code[index] = 'R36'
                    changes_school_system_name[index] = 'Orleans Parish'
                if (str(raw_row['School_Code']).strip() in ['998', '997'] or str(raw_row['Assess_Group_Type']).strip() in ['13', '05']) and (raw_row[f'Test_Taken_Flag_-_{subject}'] == 'Y' or raw_row[f'Summarized_Void_Flag_-_{subject}'] == 'Y' or raw_row[f'Launch_Flag_-_{subject}'] == 'Y'):
                    changes_lasid[index] = 'XXXXX' + str(report_row['LASID'])[5:]

    # Apply the changes to the DataFrame
    for index, value in changes_school_system_code.items():
        report_df.at[index, 'School_System_Code'] = value
    for index, value in changes_school_system_name.items():
        report_df.at[index, 'School_System_Name'] = value
    for index, value in changes_lasid.items():
        report_df.at[index, 'LASID'] = value

    return report_df

# Use the function to modify the report_df DataFrame
report_df = modify_report_data(report_df, raw_df)

In [163]:
report_df

,Page_Number,Advanced_School_Percentage,Advanced_School_System_Percentage,Advanced_State_Percentage,Mastery_School_Percentage,Mastery_School_System_Percentage,Mastery_State_Percentage,Basic_School_Percentage,Basic_School_System_Percentage,Basic_State_Percentage,Approaching_Basic_School_Percentage,Approaching_Basic_School_System_Percentage,Approaching_Basic_State_Percentage,Unsatisfactory_School_Percentage,Unsatisfactory_School_System_Percentage,Unsatisfactory_State_Percentage,Scale_Score_-_ELA,If_Voided,Report_Title,Report_Subject,Report_Season_Year,Student_Name,Summarized_Grade,LASID,School_System_Average_Score,State_Average_Score,Student_Performance_Level,School_System_Average_Level,State_Average_Level,Student_Performance_Achievement_Level,School_System_Average_Achievement_Level,State_Average_Achievement_Level_Fixed,Reading_Performance_Achievement_Level,Literary_Text_Achievement_Level,Informational_Text_Achievement_Level,Vocabulary_Achievement_Level,Writing_Performance_Achievement_Level,Written_Expression_Achievement_Level,Knowledge&Use_of_Language_Conventions,State_Average_Achievement_Level,Reading_Performance_Achievement_Level_State_Percentage_Strong,Reading_Performance_Achievement_Level_State_Percentage_Moderate,Reading_Performance_Achievement_Level_State_Percentage_Weak,Writing_Performance_Achievement_Level_State_Percentage_Strong,Writing_Performance_Achievement_Level_State_Percentage_Moderate,Writing_Performance_Achievement_Level_State_Percentage_Weak,Student_First_Name,Student_Middle_Initial,Student_Last_Name,Summarized_DOB_Day,Summarized_DOB_Month,Summarized_DOB_Year,School_Code,School_Name,School_System_Code,School_System_Name
0,22256,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,695,False,LEAP 2025,English Language Arts,Spring 2023,CHRISTIAN FRANCIS,3,7831378545,744.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,CHRISTIAN,NaN,FRANCIS,29.0,7.0,2013.0,71,Magnolia Elementary,023,Iberia Parish
1,22257,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,685,False,LEAP 2025,English Language Arts,Spring 2023,MIGUEL GAGE,3,5412525873,744.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,MIGUEL,NaN,GAGE,12.0,2.0,2012.0,71,Magnolia Elementary,023,Iberia Parish
2,22258,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,717,False,LEAP 2025,English Language Arts,Spring 2023,EZAVIEN GREEN,3,8828116684,744.0,740,2.0,3.0,3,APPROACHING BASIC,SIC,BASIC,MODERATE PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,EZAVIEN,NaN,GREEN,10.0,8.0,2014.0,71,Magnolia Elementary,023,Iberia Parish
3,22259,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,720,False,LEAP 2025,English Language Arts,Spring 2023,AYCETON HALL,3,1271283891,744.0,740,2.0,3.0,3,APPROACHING BASIC,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,AYCETON,NaN,HALL,25.0,8.0,2014.0,71,Magnolia Elementary,023,Iberia Parish
4,22260,7%,6%,6%,20%,37%,36%,22%,22%,20%,27%,18%,16%,24%,17%,22%,685,False,LEAP 2025,English Language Arts,Spring 2023,ZAKHARIA HAWK,3,8934384727,744.0,740,1.0,3.0,3,UNSATISFACTORY,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,NaN,43%,20%,37%,43%,21%,37%,ZAKHARIA,NaN,HAWK,19.0,7.0,2014.0,71,Magnolia Elementary,023,Iberia Parish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66762,66762,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,773,False,LEAP 2025,English Language Arts,Spring 2023,SKY WILLIAMS,8,4186498644,739.0,746,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,SKY,NaN,WILLIAMS,29.0,6.0,2009.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish
66763,66763,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,709,False,LEAP 2025,English Language Arts,Spring 2023,ELIJAH WILLIAMSON,8,5648689233,739.0,746,2.0,3.0,3,APPROACHING BASIC,SIC,BASIC,WEAK PERFORMANCE,STRONG PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,ELIJAH,NaN,WILLIAMSON,29.0,10.0,2007.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish
66764,66764,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,717,False,LEAP 2025,English Language Arts,Spring 2023,JONTAE WILLIS,8,9832174422,739.0,746,2.0,3.0,3,APPROACHING BASIC,SIC,BASIC,WEAK PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,WEAK PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,JONTAE,NaN,WILLIS,29.0,10.0,2008.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish
66765,66765,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,727,False,LEAP 2025,English Language Arts,Spring 2023,DEMARI WILSON,8,7326166781,739.0,746,3.0,3.0,3,BASIC,SIC,BASIC,MODERATE PERFORMANCE,WEAK PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,WEAK PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,DEMARI,NaN,WILSON,20.0,1.0,2009.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish
66766,66766,3%,8%,11%,30%,29%,37%,26%,25%,23%,25%,22%,17%,16%,15%,12%,765,False,LEAP 2025,English Language Arts,Spring 2023,CORAAN WRIGHT,8,7928932334,739.0,746,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,MODERATE PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,NaN,46%,24%,30%,46%,29%,25%,CORAAN,NaN,WRIGHT,13.0,2.0,2009.0,1,Pierre A. Capdau Charter School,R36,Orleans Parish

# 1. Calculate the average scores based on pdf report informations

In [164]:
# Define a function to round up if the number is halfway between two others
def round_half_up(x):
    x = Decimal(x).quantize(Decimal('0.00'))  # Control the precision of the division operation
    decimal_part = x - Decimal(int(x))
    if abs(decimal_part - Decimal('0.5')) < Decimal('1e-10'):
        return Decimal(ceil(x))
    else:
        return Decimal(round(x))



report_systems = report_df[['School_System_Code', 'School_System_Name']].drop_duplicates()

total_systems = raw_df['School_System_Name'].unique()

total_system_codes = raw_df['School_System_Code'].unique()

r_system_df = pd.DataFrame(report_systems)


r_system_df['Name_Is_Valid'] = r_system_df['School_System_Name'].apply(lambda x: x.strip() in ''.join(total_systems))

r_system_df['Code_Is_Valid'] = r_system_df['School_System_Code'].astype(str).apply(lambda x: x.strip() in ' '.join(total_system_codes))

# Convert the scores to numeric values
raw_df.loc[:, f"Scale_Score_-_{subject}"] = pd.to_numeric(raw_df[f"Scale_Score_-_{subject}"], errors='coerce')

# Filter the DataFrame for rows where 'Summarized_Void_Flag_-_{subject}' is not equal to 2
filtered_raw_df = raw_df[~raw_df[f'Summarized_Void_Flag_-_{subject}'].str.strip().isin(['2', '1', '4'])]



# Calculate the school system average for each grade
system_grade_avg = filtered_raw_df.groupby(['School_System_Name', 'Summarized_Grade'])[f"Scale_Score_-_{subject}"].apply(lambda x: round_half_up((Decimal(x.sum()) / Decimal(len(x))).quantize(Decimal('0.00'))))

# Convert the series to a dataframe
system_grade_avg_df = system_grade_avg.reset_index()

# Rename the columns
system_grade_avg_df.columns = ['School_System_Name', 'Grade', f'Average_Scale_Score_{subject}']

# Filter the DataFrame for rows where 'Rollup_to_State' is 'Y'
state_df = raw_df[raw_df['Rollup_to_State'] == 'Y']

# Calculate the state average for each grade
state_grade_avg = state_df.groupby('Summarized_Grade')[f"Scale_Score_-_{subject}"].apply(lambda x: round_half_up((Decimal(int(x.dropna().sum())) / Decimal(int(x.dropna().count()))).quantize(Decimal('0.00'))))

# Convert the series to a dataframe and append it to the system_grade_avg_df dataframe
state_grade_avg_df = state_grade_avg.reset_index()
state_grade_avg_df['School_System_Name'] = 'State'
state_grade_avg_df.columns = ['Grade', f'Average_Scale_Score_{subject}', 'School_System_Name']

# Append state_grade_avg_df to system_grade_avg_df
system_grade_avg_df = pd.concat([system_grade_avg_df, state_grade_avg_df], ignore_index=True)

In [165]:
filtered_raw_df[f'Summarized_Void_Flag_-_{subject}'].value_counts()

Summarized_Void_Flag_-_ELA
     279938
Name: count, dtype: int64

In [166]:
system_grade_avg_df.tail(6)

    School_System_Name  Grade Average_Scale_Score_ELA
993              State      3                     740
994              State      4                     744
995              State      5                     741
996              State      6                     741
997              State      7                     743
998              State      8                     746

In [167]:
nan_rows_df = system_grade_avg_df[system_grade_avg_df[f'Average_Scale_Score_{subject}'].isna()]


system_grade_avg_df = system_grade_avg_df.dropna(subset=[f'Average_Scale_Score_{subject}'])

In [168]:
dataframes = {}
dataframes[subject] = system_grade_avg_df

In [169]:
system_grade_avg_df.loc[:, 'School_System_Name'] = system_grade_avg_df['School_System_Name'].str.strip()

school_system_name = 'Jefferson Parish'  # Replace this with the name of the school system you're interested in
filtered_df = system_grade_avg_df[system_grade_avg_df['School_System_Name'] == school_system_name]
filtered_df

    School_System_Name  Grade Average_Scale_Score_ELA
412   Jefferson Parish      3                     730
413   Jefferson Parish      4                     736
414   Jefferson Parish      5                     734
415   Jefferson Parish      6                     736
416   Jefferson Parish      7                     741
417   Jefferson Parish      8                     742

# 2. Calculate the percentage of students at each achievement level

## calculate school levels

In [170]:
# Define the achievement levels to include in the calculation
achievement_levels = ['ADV', 'MAS', 'BAS', 'APP', 'UNS']

# Filter the raw_df DataFrame
filtered_raw_df = raw_df[raw_df['School_Name'].str.strip().isin(r_school_df['School_Name']) & raw_df[f'Assessment_Achievement_Level_-_{subject}'].str.strip().isin(achievement_levels)]

# Calculate the counts for each school, grade, and subject
counts_df = filtered_raw_df.groupby(['School_Name', 'Summarized_Grade', f'Assessment_Achievement_Level_-_{subject}']).size().unstack(fill_value=0)

# Calculate the percentage of students at each achievement level for each school, grade, and subject
school_grade_subject_level_df = counts_df.div(counts_df.sum(axis=1), axis=0).applymap(lambda x: Decimal(str(x)))

# Calculate the total count for each (School_Name, Summarized_Grade) group
total_counts_df = counts_df.sum(axis=1)


# Define the format_percentage function to take an additional total_count parameter
def format_percentage(x, total_count):
    if total_count < 10:
        return 'NR'
    elif x < Decimal('0.01') or round(x * 100) == 1:
        return '≤1%'
    else:
        percentage = x * 100
        return f'{percentage.quantize(Decimal("1"), rounding=ROUND_HALF_UP)}%'

# Apply the function to the dataframe
formatted_school_grade_subject_level_df = school_grade_subject_level_df.apply(lambda x: x.apply(format_percentage, total_count=total_counts_df.loc[x.name]), axis=1)

In [171]:
school_grade_subject_level_df.loc['The Delores Taylor Arthur School for You']

Assessment_Achievement_Level_-_ELA  ADV  APP  BAS  MAS  UNS
Summarized_Grade
8                                   0.0  1.0  0.0  0.0  0.0

In [172]:
formatted_school_grade_subject_level_df.loc['The Delores Taylor Arthur School for You']

Assessment_Achievement_Level_-_ELA ADV APP BAS MAS UNS
Summarized_Grade
8                                   NR  NR  NR  NR  NR

## calculate school system levels

In [173]:
# Filter the raw_df DataFrame
filtered_raw_df_system = raw_df[raw_df['School_System_Name'].str.strip().isin(r_system_df['School_System_Name']) & raw_df[f'Assessment_Achievement_Level_-_{subject}'].str.strip().isin(achievement_levels)]

# Calculate the counts for each school system, grade, and subject
counts_df_system = filtered_raw_df_system.groupby(['School_System_Name', 'Summarized_Grade', f'Assessment_Achievement_Level_-_{subject}']).size().unstack(fill_value=0)

# Calculate the percentage of students at each achievement level for each school system, grade, and subject
school_system_grade_subject_level_df = counts_df_system.div(counts_df_system.sum(axis=1), axis=0).applymap(lambda x: Decimal(str(x)))

# Calculate the total count for each (School_System_Name, Summarized_Grade) group
total_counts_df_system = counts_df_system.sum(axis=1)

# Apply the function to the dataframe
formatted_school_system_grade_subject_level_df = school_system_grade_subject_level_df.apply(lambda x: x.apply(format_percentage, total_count=total_counts_df_system.loc[x.name]), axis=1)

In [174]:
formatted_school_system_grade_subject_level_df

Assessment_Achievement_Level_-_ELA                         ADV  APP  BAS  MAS  \
School_System_Name                       Summarized_Grade
Caddo Parish                             3                  6%  17%  18%  30%
                                         4                  7%  23%  24%  26%
                                         5                  3%  26%  27%  30%
                                         6                  8%  28%  26%  22%
                                         7                 16%  24%  22%  18%
...                                                        ...  ...  ...  ...
West Carroll Parish                      4                  7%  22%  25%  35%
                                         5                 ≤1%  34%  27%  29%
                                         6                 ≤1%  23%  37%  29%
                                         7                  3%  18%  30%  33%
                                         8                  9%  18%  21%  43%

Assessment_Achievement_Level_-_ELA                         UNS
School_System_Name                       Summarized_Grade
Caddo Parish                             3                 29%
                                         4                 20%
                                         5                 15%
                                         6                 16%
                                         7                 19%
...                                                        ...
West Carroll Parish                      4                 11%
                                         5                  9%
                                         6                 10%
                                         7                 16%
                                         8                  9%

[126 rows x 5 columns]

## calculate state levels

In [175]:
# Filter the raw_df DataFrame for rows where 'Rollup_to_State' is 'Y' and 'Assessment_Achievement_Level_-_{subject}' is in achievement_levels
filtered_raw_df_state = raw_df[(raw_df['Rollup_to_State'] == 'Y') & (raw_df[f'Assessment_Achievement_Level_-_{subject}'].str.strip().isin(achievement_levels))]

# Calculate the counts for each grade and subject
counts_df_state = filtered_raw_df_state.groupby(['Summarized_Grade', f'Assessment_Achievement_Level_-_{subject}']).size().unstack(fill_value=0)

# Calculate the percentage of students at each achievement level for each grade and subject
state_grade_subject_level_df = counts_df_state.div(counts_df_state.sum(axis=1), axis=0).applymap(lambda x: Decimal(str(x)))

# Calculate the total count for each Summarized_Grade
total_counts_df_state = counts_df_state.sum(axis=1)

# Apply the function to the dataframe
formatted_state_grade_subject_level_df = state_grade_subject_level_df.apply(lambda x: x.apply(format_percentage, total_count=total_counts_df_state.loc[x.name]), axis=1)

In [176]:
formatted_state_grade_subject_level_df

Assessment_Achievement_Level_-_ELA  ADV  APP  BAS  MAS  UNS
Summarized_Grade
3                                    6%  16%  20%  36%  22%
4                                   10%  19%  24%  34%  12%
5                                    3%  20%  29%  37%  10%
6                                    7%  22%  28%  32%  10%
7                                   15%  18%  25%  27%  15%
8                                   11%  17%  23%  37%  12%

In [177]:
counts_df_state

Assessment_Achievement_Level_-_ELA   ADV   APP    BAS    MAS    UNS
Summarized_Grade
3                                   3076  8052   9625  17976  10628
4                                   5031  9402  11856  16563   6035
5                                   1426  9827  14140  18084   4842
6                                   3093  9701  12349  13829   4410
7                                   6301  7794  10482  11596   6296
8                                   4894  7642  10741  16847   5669

In [178]:
state_grade_subject_level_df

Assessment_Achievement_Level_-_ELA,ADV,APP,BAS,MAS,UNS
Summarized_Grade,,,,,
3,0.06232145389711692,0.16313795408959217,0.19500780031201248,0.3642036590554531,0.21532913264582532
4,0.10291079428068811,0.19232106695031398,0.24251846094053633,0.33880172643033934,0.1234479513981222
5,0.0295122001697055,0.2033775533434053,0.29263850659160995,0.374262712390571,0.1002090275047083
6,0.07129685122862016,0.2236180904522613,0.28465723110967683,0.3187727628970541,0.10165506431238763
7,0.14836704419694366,0.18352209847182652,0.246815324118769,0.27304622195012834,0.1482493112623325
8,0.10687222938003625,0.16688140108750246,0.2345554997488699,0.36789465638853097,0.12379621339506038

In [179]:
total_counts_df_state

Summarized_Grade
3    49357
4    48887
5    48319
6    43382
7    42469
8    45793
dtype: int64

# Comparison Part

In [180]:
def convert_to_str(value):
    try:
        # Try to convert to int first to remove decimal points
        return str(int(value))
    except ValueError:
        # If it's not a number, just convert to string
        return str(value)

In [195]:
# Keep only the rows in raw_df where the School_Name is in r_school_names
raw_audit_df = raw_audit_df[raw_audit_df['School_Name'].isin(r_school_names)]

start_time = time.time()
# Define a dictionary to map the full names to the abbreviations
level_mapping = {
    'Advanced': 'ADV',
    'Mastery': 'MAS',
    'Basic': 'BAS',
    'Approaching_Basic': 'APP',
    'Unsatisfactory': 'UNS'
}

# Define a dictionary to map the raw data values to the report data values
rating_mapping = {
    '1': 'WEAK PERFORMANCE',
    '2': 'MODERATE PERFORMANCE',
    '3': 'STRONG PERFORMANCE',
    '': ''
    
}



# Create an empty list to store the discrepancies
discrepancies = []

# Convert LASID in raw_df to a set for faster lookup
raw_lasid_set = set(raw_df['LASID'])



# Create a dictionary from raw_df for faster access
raw_dict = defaultdict(list)
for i, row in raw_audit_df.iterrows():
    raw_dict[row['LASID']].append(row)


# Record the end time
end_time = time.time()

# Calculate and print the running time
running_time = end_time - start_time
print(f"Running time: {running_time} seconds")

Running time: 0.3296048641204834 seconds

In [196]:
discrepancies = []

start_time = time.time()
# Iterate over the rows in report_df
for index, report_row in tqdm(report_df.iterrows(), total=report_df.shape[0]):
    lasid = report_row['LASID']
    # Check if the LASID exists in raw_df
    if lasid not in raw_lasid_set:
        continue

    # Get the corresponding rows in the raw_df DataFrame
    raw_rows = raw_dict[lasid]
    
    # Iterate over the raw_rows
    for raw_row in raw_rows:
        
        # Check if the ELA score matches
        raw_value = pd.to_numeric(raw_row[f'Scale_Score_-_{subject}'], errors='coerce')
        report_value = pd.to_numeric(report_row[f'Scale_Score_-_{subject}'], errors='coerce')
        if raw_value != report_value:
            continue

   
        # Compare the personal information
        for column in ['Student_First_Name', 'Student_Last_Name', 'Summarized_DOB_Month', 
                       'Summarized_DOB_Day', 'Summarized_DOB_Year', 'Summarized_Grade', 'School_Name', 
                       'School_Code', 'School_System_Name', 'School_System_Code']:
           # Then in your comparison code, use this function to convert values to strings:
            report_value = convert_to_str(report_row[column]).strip()
            raw_value = convert_to_str(raw_row[column]).strip()
            if pd.isnull(report_value) and pd.isnull(raw_value):
                continue
            elif column in ['Summarized_DOB_Month', 'Summarized_DOB_Day', 'Summarized_DOB_Year']:
                # If the raw data is empty, skip the comparison
                if raw_value == '':
                    continue
                # Convert both values to integers before comparing
                if pd.to_numeric(report_value, errors='coerce') != pd.to_numeric(raw_value, errors='coerce'):
                    discrepancy = f"{column} does not match"
                    discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                          'Discrepancy': discrepancy, 'Report_Data': report_value, 'Raw_Data': raw_value})
            elif column == 'Student_First_Name':
                # Check if the raw data matches the first letter of the first name
                if raw_value == report_value[0]:
                    continue
                if raw_value != report_value[0]:
                    if raw_value != report_value:
                        if raw_value != report_value[:8]:
                            discrepancy = f"{column} does not match"
                            discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                                  'Discrepancy': discrepancy, 'Report_Data': report_value, 'Raw_Data': raw_value})
            elif column == 'Student_Last_Name':
                # Check if the raw data matches the first three letters of the last name
                if raw_value == report_value[0]:
                    continue
                if raw_value != report_value[:3]:
                    if raw_value != report_value:
                        if raw_value != report_value[:12]:
                            discrepancy = f"{column} does not match"
                            discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                                  'Discrepancy': discrepancy, 'Report_Data': report_value, 'Raw_Data': raw_value})
            elif column == 'School_System_Code':
                # Check if the raw data is a zero-padded version of the report data
                if raw_value != report_value and raw_value.lstrip('0') != report_value:
                    discrepancy = f"{column} does not match"
                    discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                          'Discrepancy': discrepancy, 'Report_Data': report_value, 'Raw_Data': raw_value})
            else:
                if report_value != raw_value:
                    discrepancy = f"{column} does not match"
                    discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                          'Discrepancy': discrepancy, 'Report_Data': report_value, 'Raw_Data': raw_value})
        # Compare the scores

        # Check if the raw data for this subject is valid
        raw_value = pd.to_numeric(raw_row[f'Scale_Score_-_{subject}'], errors='coerce')
        report_value = pd.to_numeric(report_row[f'Scale_Score_-_{subject}'], errors='coerce')
        if pd.isnull(report_value) and pd.isnull(raw_value):
            continue
        elif report_value != raw_value:
            discrepancy = f"{subject} score does not match"
            discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                  'Discrepancy': discrepancy, 'Report_Data': report_value, 'Raw_Data': raw_value})

        # Compare the additional columns
        for column_raw, column_report in [('Reading_Rating_', 'Reading_Performance_Achievement_Level'), 
                                          ('Literary_Text_Rating', 'Literary_Text_Achievement_Level'), 
                                          ('Informational_Text_Rating', 'Informational_Text_Achievement_Level'), 
                                        ('Vocabulary_Rating', 'Vocabulary_Achievement_Level'), 
                                          ('Written_Expression_Rating', 'Written_Expression_Achievement_Level'), 
                                          ('Knowledge_&_Use_of_Language_Conventions_Rating', 'Knowledge&Use_of_Language_Conventions'), 
                                          ('Writing_Rating', 'Writing_Performance_Achievement_Level'), 
                                         ]:
            raw_value = raw_row[column_raw]
            report_value = report_row[column_report]
            # Convert the raw value using the mapping
            raw_value_converted = rating_mapping.get(raw_value, 'Unknown')
            # If raw_value_converted is blank and report_value is 'NaN' or blank, continue to the next iteration
            if (raw_value.strip() == '' or pd.isna(raw_value) ) and (str(report_value).lower().strip() == 'nan' or report_value.strip() == '' or pd.isna(report_value)):
                continue
            elif raw_value_converted.strip() != report_value.strip():
                discrepancy = f"{column_report} does not match"
                discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                      'Discrepancy': discrepancy, 'Report_Data': report_value, 'Raw_Data': raw_value})
#                print(raw_row[f'Test_Taken_Flag_-_{subject}'], raw_row[f'Summarized_Void_Flag_-_{subject}'], raw_row[f'Launch_Flag_-_{subject}'])


        # Compare the average scores
        system_grade_avg_row = system_grade_avg_df[(system_grade_avg_df['School_System_Name'] == report_row['School_System_Name']) & 
                                                   (system_grade_avg_df['Grade'] == report_row['Summarized_Grade'])]
        if not system_grade_avg_row.empty:
            system_grade_avg_row = system_grade_avg_row.iloc[0]
            report_value = report_row['School_System_Average_Score']
            # Check if the report_value is NaN before proceeding
            if pd.isnull(report_value):
                continue
            raw_value = system_grade_avg_row[f'Average_Scale_Score_{subject}']
            if pd.isnull(report_value) and pd.isnull(raw_value):
                continue
            elif report_value != raw_value:
                discrepancy = f"{subject} school system average score does not match"
                discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                      'Discrepancy': discrepancy, 'Report_Data': report_value, 'Raw_Data': raw_value})

        # Compare the state average scores
        state_avg_row = system_grade_avg_df[(system_grade_avg_df['School_System_Name'] == 'State') & 
                                            (system_grade_avg_df['Grade'] == report_row['Summarized_Grade'])]
        if not state_avg_row.empty:
            state_avg_row = state_avg_row.iloc[0]
            report_value = report_row['State_Average_Score']
            raw_value = state_avg_row[f'Average_Scale_Score_{subject}']
            if pd.isnull(report_value) and pd.isnull(raw_value):
                continue
            elif report_value != raw_value:
                discrepancy = f"{subject} State average score does not match"
                discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                      'Discrepancy': discrepancy, 'Report_Data': report_value, 'Raw_Data': raw_value})

        # Use the mapping in the loop
        for level in ['Advanced', 'Mastery', 'Basic', 'Approaching_Basic', 'Unsatisfactory']:
            # Get the corresponding row from the level DataFrame
            level_row = formatted_school_grade_subject_level_df.loc[[(raw_row['School_Name'], raw_row['Summarized_Grade'])]]
            level_row_system = formatted_school_system_grade_subject_level_df.loc[[(raw_row['School_System_Name'], raw_row['Summarized_Grade'])]]
            level_row_state = formatted_state_grade_subject_level_df.loc[[raw_row['Summarized_Grade']]]
            
            # Get the abbreviation for the level
            level_abbrev = level_mapping[level]



            # Calculate the difference between the report data and the raw data for this level
            if pd.isna(report_row[f'{level}_School_Percentage']) and pd.isna(level_row[level_abbrev].iloc[0]):
                continue
            else:
                # Compare the percentage strings directly
                report_percentage = report_row[f'{level}_School_Percentage']
                level_percentage = level_row[level_abbrev].iloc[0]
                if report_percentage != level_percentage:
                    discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                          'Discrepancy': f"{level} school percentage does not match", 
                                          'Report_Data': report_row[f'{level}_School_Percentage'], 'Raw_Data': level_row[level_abbrev].iloc[0]})

            # Calculate the difference between the report data and the raw data for this level
            if pd.isna(report_row[f'{level}_School_System_Percentage']) and pd.isna(level_row_system[level_abbrev].iloc[0]):
                continue
            else:
                # Compare the percentage strings directly
                report_percentage_system = report_row[f'{level}_School_System_Percentage']
                level_percentage_system = level_row_system[level_abbrev].iloc[0]
                if report_percentage_system != level_percentage_system:
                    discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                          'Discrepancy': f"{level} school system percentage does not match", 
                                          'Report_Data': report_row[f'{level}_School_System_Percentage'], 'Raw_Data': level_row_system[level_abbrev].iloc[0]})

            if pd.isna(report_row[f'{level}_State_Percentage']) and pd.isna(level_row_state[level_abbrev].iloc[0]):
                continue
            else:
                # Compare the percentage strings directly
                report_percentage_state = report_row[f'{level}_State_Percentage']
                level_percentage_state = level_row_state[level_abbrev].iloc[0]
                if report_percentage_state != level_percentage_state:
                    discrepancies.append({'LASID': lasid, 'Student_Name': report_row['Student_Name'], 
                                          'Discrepancy': f"{level} state percentage does not match", 
                                          'Report_Data': report_row[f'{level}_State_Percentage'], 'Raw_Data': level_row_state[level_abbrev].iloc[0]})


        
        
# Convert the list of discrepancies to a DataFrame
discrepancies_df = pd.DataFrame(discrepancies)

# Record the end time
end_time = time.time()

# Calculate and print the running time
running_time = end_time - start_time
print(f"Running time: {running_time} seconds")

# Print the discrepancies
discrepancies_df

100%|███████████████████████████████████████████████████████████████████████████| 66767/66767 [01:53<00:00, 590.82it/s]

Running time: 113.00878763198853 seconds

,LASID,Student_Name,Discrepancy,Report_Data,Raw_Data
0,----------,NO NAME PROVIDED,Student_First_Name does not match,NO,
1,----------,NO NAME PROVIDED,Student_Last_Name does not match,nan,
2,----------,NO NAME PROVIDED,Summarized_DOB_Month does not match,nan,--
3,----------,NO NAME PROVIDED,Summarized_DOB_Day does not match,nan,--
4,----------,NO NAME PROVIDED,Summarized_DOB_Year does not match,nan,----
5,----------,NO NAME PROVIDED,Student_First_Name does not match,NO,
6,----------,NO NAME PROVIDED,Student_Last_Name does not match,nan,
7,----------,NO NAME PROVIDED,Summarized_DOB_Month does not match,nan,--
8,----------,NO NAME PROVIDED,Summarized_DOB_Day does not match,nan,--
9,----------,NO NAME PROVIDED,Summarized_DOB_Year does not match,nan,----

pd.set_option('display.max_rows', None)
discrepancies_df

In [197]:
# Create a new list to store the updated discrepancies
updated_discrepancies = []

# Iterate over the discrepancies
for discrepancy in discrepancies:
    # Get the LASID
    lasid = discrepancy['LASID']
    
    # Get the corresponding row in the raw_df DataFrame
    raw_row = raw_df[raw_df['LASID'] == lasid].iloc[0]
    
    # Check if the 'Show_'N/A'_in_place_of_School_System_results_on_school_reports' field is 'Y'
    if raw_row["Show_'N/A'_in_place_of_School_System_results_on_school_reports"] == 'Y':
        # Check if the Report_Data value for this discrepancy is NaN
        if pd.isnull(discrepancy['Report_Data']):
            # If it is, skip this discrepancy
            continue
            
        
    
    # If the discrepancy wasn't skipped, add it to the updated discrepancies list
    updated_discrepancies.append(discrepancy)

# Convert the updated discrepancies list to a DataFrame
updated_discrepancies_df = pd.DataFrame(updated_discrepancies)

# Print the updated discrepancies
updated_discrepancies_df

,LASID,Student_Name,Discrepancy,Report_Data,Raw_Data
0,----------,NO NAME PROVIDED,Student_First_Name does not match,NO,
1,----------,NO NAME PROVIDED,Student_Last_Name does not match,nan,
2,----------,NO NAME PROVIDED,Summarized_DOB_Month does not match,nan,--
3,----------,NO NAME PROVIDED,Summarized_DOB_Day does not match,nan,--
4,----------,NO NAME PROVIDED,Summarized_DOB_Year does not match,nan,----
5,----------,NO NAME PROVIDED,Student_First_Name does not match,NO,
6,----------,NO NAME PROVIDED,Student_Last_Name does not match,nan,
7,----------,NO NAME PROVIDED,Summarized_DOB_Month does not match,nan,--
8,----------,NO NAME PROVIDED,Summarized_DOB_Day does not match,nan,--
9,----------,NO NAME PROVIDED,Summarized_DOB_Year does not match,nan,----

In [198]:
# Assuming 'LASID' is the column name in discrepancies_df
updated_discrepancies_df = updated_discrepancies_df[updated_discrepancies_df['LASID'] != '----------']

updated_discrepancies_df

Empty DataFrame
Columns: [LASID, Student_Name, Discrepancy, Report_Data, Raw_Data]
Index: []

In [79]:
len(discrepancies_df['LASID'].unique())

224

In [44]:
print(report_df[report_df['LASID'] == '2755822848'].values)

[[38883 '42%' '8%' '7%' '50%' '25%' '32%' '6%' '26%' '28%' '≤1%' '25%'
  '22%' '≤1%' '16%' '10%' '740' False 'LEAP 2025' 'English Language Arts'
  'Spring 2023' 'SOPHIA AGUILUZ' 6 '2755822848' 736.0 741 3.0 3.0 3
  'BASIC' 'SIC' 'BASIC' 'MODERATE PERFORMANCE' ' STRONG PERFORMANCE'
  ' MODERATE PERFORMANCE' ' WEAK PERFORMANCE' ' MODERATE PERFORMANCE'
  ' MODERATE PERFORMANCE' ' MODERATE PERFORMANCE' nan '38%' '30%' '32%'
  '46%' '23%' '31%' 'SOPHIA' nan 'AGUILUZ' 21.0 8.0 2011.0 105
  'Patrick F. Taylor Science & Technology A' '026' 'Jefferson Parish']]

In [80]:
report_df[report_df['LASID'] == '4594497268']

,Page_Number,Advanced_School_Percentage,Advanced_School_System_Percentage,Advanced_State_Percentage,Mastery_School_Percentage,Mastery_School_System_Percentage,Mastery_State_Percentage,Basic_School_Percentage,Basic_School_System_Percentage,Basic_State_Percentage,Approaching_Basic_School_Percentage,Approaching_Basic_School_System_Percentage,Approaching_Basic_State_Percentage,Unsatisfactory_School_Percentage,Unsatisfactory_School_System_Percentage,Unsatisfactory_State_Percentage,Scale_Score_-_ELA,If_Voided,Report_Title,Report_Subject,Report_Season_Year,Student_Name,Summarized_Grade,LASID,School_System_Average_Score,State_Average_Score,Student_Performance_Level,School_System_Average_Level,State_Average_Level,Student_Performance_Achievement_Level,School_System_Average_Achievement_Level,State_Average_Achievement_Level_Fixed,Reading_Performance_Achievement_Level,Literary_Text_Achievement_Level,Informational_Text_Achievement_Level,Vocabulary_Achievement_Level,Writing_Performance_Achievement_Level,Written_Expression_Achievement_Level,Knowledge&Use_of_Language_Conventions,State_Average_Achievement_Level,Reading_Performance_Achievement_Level_State_Percentage_Strong,Reading_Performance_Achievement_Level_State_Percentage_Moderate,Reading_Performance_Achievement_Level_State_Percentage_Weak,Writing_Performance_Achievement_Level_State_Percentage_Strong,Writing_Performance_Achievement_Level_State_Percentage_Moderate,Writing_Performance_Achievement_Level_State_Percentage_Weak,Student_First_Name,Student_Middle_Initial,Student_Last_Name,Summarized_DOB_Day,Summarized_DOB_Month,Summarized_DOB_Year,School_Code,School_Name,School_System_Code,School_System_Name
9096,9096,8%,3%,3%,77%,35%,37%,11%,28%,29%,5%,22%,20%,≤1%,13%,10%,753,False,LEAP 2025,English Language Arts,Spring 2023,CHARLI ADAMS,5,4594497268,738.0,741,4.0,3.0,3,MASTERY,SIC,BASIC,STRONG PERFORMANCE,STRONG PERFORMANCE,MODERATE PERFORMANCE,MODERATE PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,STRONG PERFORMANCE,NaN,41%,28%,31%,41%,27%,32%,CHARLI,NaN,ADAMS,16.0,5.0,2012.0,84,B. R. Foreign Language Acad. Immersion M,017,East Baton Rouge Parish

In [134]:
raw_audit_df[raw_audit_df['LASID'] == '5147244581']

,School_System_Code,School_Code,School_System_Name,School_Name,DRC_Unique_Student_ID,Student_Last_Name,Student_First_Name,Student_Middle_Initial,LASID,Summarized_Grade,Summarized_DOB_Month,Summarized_DOB_Day,Summarized_DOB_Year,Scale_Score_-_ELA,Assessment_Achievement_Level_-_ELA,Literary_Text_Rating,Informational_Text_Rating,Vocabulary_Rating,Written_Expression_Rating,Knowledge_&_Use_of_Language_Conventions_Rating,Reading_Rating_,Writing_Rating,Test_Taken_Flag_-_ELA,Summarized_Void_Flag_-_ELA,Assess_Group_Type,Launch_Flag_-_ELA,Rollup_to_State,Summarize_to_Assessment_Group_Code_for_School_System_level_reporting,Show_'N/A'_in_place_of_School_System_results_on_school_reports,Site_Report_Code
31713,026,30,Jefferson Parish,Emmett C.Gilbert School of Excellence at,101416,ALEXANDER,KYA,,5147244581,3,09,19,2013,,,,,,,,,,N,,1,N,Y,N,N,026

In [133]:
raw_df[raw_df['LASID'] == '5147244581']

,School_System_Code,School_Code,School_System_Name,School_Name,DRC_Unique_Student_ID,Student_Last_Name,Student_First_Name,Student_Middle_Initial,LASID,Summarized_Grade,Summarized_DOB_Month,Summarized_DOB_Day,Summarized_DOB_Year,Scale_Score_-_ELA,Assessment_Achievement_Level_-_ELA,Literary_Text_Rating,Informational_Text_Rating,Vocabulary_Rating,Written_Expression_Rating,Knowledge_&_Use_of_Language_Conventions_Rating,Reading_Rating_,Writing_Rating,Test_Taken_Flag_-_ELA,Summarized_Void_Flag_-_ELA,Assess_Group_Type,Launch_Flag_-_ELA,Rollup_to_State,Summarize_to_Assessment_Group_Code_for_School_System_level_reporting,Show_'N/A'_in_place_of_School_System_results_on_school_reports,Site_Report_Code
166379,017,128,East Baton Rouge Parish,Capitol Elementary School,101415,ALE,K,,5147244581,3,,19,,747.0,BAS,3,2,2,2,1,3,2,Y,,1,,Y,N,N,017